pipeline{
  agent any
  
  stages{
    stage('Checkout'){
      steps{
        git branch: 'main',
        url:'https://github.com/nikitaaaa07/PES1UG21CS385_Jenkins.git'
      }
    }
    stage('Build'){
      steps{
        build 'PES1UG21CS385-1'
        sh 'g++ hello2.cpp -o output'
      }
    }
    stage('Test'){
      steps{
        sh './output'
      }
    }
    stage('Deploy'){
      steps{
        echo 'deploy'
      }
    }
  }
    post{
      failure{
        error 'Pipeline failed'
      }
    }
  }
